#!/usr/bin/env bash

if [ ! $0 == ${BASH_SOURCE[0]} ]; then
     echo >&2 "[${BASH_SOURCE[0]}] must be called, not sourced"
     return 101
elif [ ! ${0:0:1} == /   ]; then
     echo >&2 "[$0]: must be called with full pathname"
     exit 102
elif [ $(readlink $0) ]; then
     echo >&2 "[$0]: must not be symlinked"
     exit 103
fi

here=$(dirname $0)
flat=$here/flat
bin=${KT_BIN:-$HOME/.local/bin}
[ $1. == --test. ] && bin=$here/.tmpbin
[ $1. == --test. ] && shift
mkdir -p $bin
rm $bin/.k0*
for real in $(ls $flat/k0*); do
    link=$bin/.$(basename $real)
    echo "}}}" ln -s $real $link
    ln -s $real $link
done
