#!/usr/bin/env bash

# 
#     KT  -- Tests for K.
#
#   All our environment variables should start with the
#   prefix "KT_" except for the evironment variable
#   "KT" which names this directory.
#
#   We do due diligence and guarantee *NOW* that our
#   environment is set right. 
#
#   XXX we assume we were not sourced by symlink.
#

_export () { export $1="$2"; }

pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null
_export KT $PWD
popd > /dev/null

sandbox=$PWD/sandbox
the_exp_dir=$PWD/regress.exp
the_got_dir=$HOME/.tmp.test.k0/regress.got
source $PWD/lib/functions.sh     
source $PWD/lib/hooks.sh

