#!/usr/bin/env bash

if [ ! $0 == ${BASH_SOURCE[0]} ]; then
     echo >&2 "[${BASH_SOURCE[0]}] must be called, not sourced"
     return 101
elif [ ! ${0:0:1} == /   ]; then
     echo >&2 "[$0]: must be called with full pathname"
     exit 102
elif [ $(readlink $0) ]; then
     echo >&2 "[$0]: must not be symlinked"
     exit 103
fi

here=$(dirname $0)
bin=${KT_BIN:-$HOME/.local/bin}
if [ $1. == --test. ]; then
    bin=$here/.tmpbin
    shift
fi

################################################################

_export () { export $1="$2"; }

isolated () {
    local acc=
    for part in $(echo $PATH | tr ':' ' '); do
        [ ${part:0:${#HOME}} == $HOME ] && continue
        acc=$acc:$part
    done
    acc=${acc:1}
    echo $acc
}

###############################################################

_export KT          $here
_export KT_BIN      $bin
_export KT_SANDBOX  $KT/sandbox
_export KT_EXP      $KT/regress.exp
_export KT_GOT      $HOME/.tmp.test.k0/regress.got
_export KT_TESTS    $KT/tests
_export KT_SHUNIT2  $KT/vendor/shunit2/shunit2/shunit2
_export PATH        $KT:$KT_BIN:$KT/bin:$(isolated)

###############################################################

if [ ! -f $0.d/$1 ]; then
    for name in $(ls $0.d); do
       echo try: kt $name
    done
    exit 99
fi

$(dirname $KT)/install
$0.d/$@
exit $?
