#!/usr/bin/env bash

_export () { export $1="$2";  }

_export bs0   ${BASH_SOURCE[0]}
_export name $(basename $bs0)
_export bin  ~/.local/bin
_export here 

[ ! $0 == $bs0    ] && >&2 echo "[$bs0]: must be called, not sourced"
[ ! $0 == $bs0    ] && return 1
[   $0 == ./$name ] && here=$PWD
[ ${0:0:1} == /   ] && here=$(dirname $0)
[ -z $here        ] && >&2 echo "[$0]: must be called with full pathname"
[ -z $here        ] && exit 2

if [ $1. == --bin. ]; then
    [ -z $2 ] && >&2 echo "[$0]: --bin flag requires an argument"
    [ -z $2 ] && exit 3
    bin=$2
    shift 2
    echo [$0]: using --bin $bin
    $(dirname $here)/install --bin $bin
fi
