#!/usr/bin/env bash

source kt.init

suite() {
    local file
    local function
    for file in $(ls $KT_TESTS/test_*); do  
        echo source $file
        source $file
    done
    for function in $(set | grep ^test_ | cut -d' ' -f1); do
        suite_addTest $function
    done
    for function in $(set | grep ^test- | cut -d' ' -f1); do
        suite_addTest $function
    done
}

. .k0.shunit2 2> /dev/null #$PWD/tmp.err.out

